### ISSUE TITLE
Help me backend eon 

### ISSUE THREAD

**Issue by NuZiuki240Hz** [hereswhisper/EonBackend#3]
Help me backend eon start 
![image](https://github.com/user-attachments/assets/d51b27c4-ed3e-4243-a7a7-79c73f7fd956)

**Comment by 4lxprime** [comment]
This issue is pretty common with javascript and typescript, you need to execute `npm i` (that will install all required packages) and `npm build` (that will convert typescript code to javascript) before running the command `npm start` (which is the command started by the start.bat). `npm i` have to be executed just once and `npm build` should be executed after any changes in the code.
